### ISSUE TITLE
chmod and chown changes

### ISSUE THREAD

**Issue by rusty1281** [cstaelen/tidarr#22]
First of all, great work on the project! Love the UI and the way the solution works. Excellent and functional integration with Plex! I do have one question on that matter.

I have noticed that the container does not work unless its running as `root` user. Including if I specify a `user= uid:gid`  parametar. As a result the download works fine, but the owner is `root:root` with chmod `0000`. 

Is there a way to change this up front? I want the content to be able to land with a non root account and a different 755 or 777 chmod if possible.

Am I missing something here?

Thanks in advance!

**Comment by cstaelen** [comment]
Hi there, thanks for your message 🙏 
Indeed, you should be able to use default env vars provided by the linuxserver.io image I used to build tidarr.

Could you please try with those params in your `docker-compose.yml`   :

```
   environment:
      - PUID=<value>
      - PGID=<value>
```

If that does not change anything, i will investigate :)

**Comment by rusty1281** [comment]
> Hi there, thanks for your message 🙏 Indeed, you should be able to use default env vars provided by the linuxserver.io image I used to build tidarr.
> 
> Could you please try with those params in your `docker-compose.yml` :
> 
> ```
>    environment:
>       - PUID=<value>
>       - PGID=<value>
> ```
> 
> If that does not change anything, i will investigate :)

While I was waiting for your reply I noticed in the source that those variables can be used. Tried it, and the container starts, but the end result with files is still the same. `root:root` with permissions 0000.

**Comment by cstaelen** [comment]
Ok thanks for the feedback !
I will investigate this point 👍

**Comment by cstaelen** [comment]
Could you please send me more details about your setup ? 

- Part of the `docker-compose.yml`concerned by Tidarr container
- OS  / Device
- Do you have specific docker setup ? Like `rootless` mode activated  or something else ?

**Comment by rusty1281** [comment]
> Could you please send me more details about your setup ?
> 
> * Part of the `docker-compose.yml`concerned by Tidarr container
> * OS  / Device
> * Do you have specific docker setup ? Like `rootless` mode activated  or something else ?

compose is this:

```
services:
    tidarr:
        image: cstaelen/tidarr
        container_name: 'tidarr'
        ports:
            - 8484:8484
        volumes:
            - /volume1/docker/tidarr/config:/home/app/standalone/shared
            - /volume1/Plex Music:/home/app/standalone/download/albums
        environment:
            - PUID=1026
            - PGID=100
            - ENABLE_PLEX_UPDATE=true
            - PLEX_URL=http://xxxxxxxxx
            - PLEX_LIBRARY=xxx
            - PLEX_TOKEN=xxxxxxxxx
        restart: 'unless-stopped'
```

This is running on a Synology NAS with DSM 7.2.2. version. Linux version under it is 4.4.302+. The Docker setup installed is version 20.10.23.

Setup is not rootless by default
